#!/usr/bin/env python
"""Minimal reproduction runner scaffold generated by paper-repro-agent."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def run_baseline(outputs: Path) -> None:
    tables = outputs / "tables"
    tables.mkdir(parents=True, exist_ok=True)
    path = tables / "baseline_metrics.csv"
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["metric", "paper_value", "reproduced_value", "note"])
        writer.writerow(["todo", "", "", "Fill after implementing the paper-specific baseline."])
    print(f"Wrote {path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Run paper reproduction stages.")
    parser.add_argument("--stage", choices=["baseline", "core", "all"], default="baseline")
    parser.add_argument("--outputs", type=Path, default=Path("outputs"))
    args = parser.parse_args()

    if args.stage in {"baseline", "all"}:
        run_baseline(args.outputs)
    if args.stage in {"core", "all"}:
        print("Core method is paper-specific. Implement it after completing outputs/reproduction_spec.md.")


if __name__ == "__main__":
    main()
